---
- name: Enable Mongod
  service:
    name: mongod
    enabled: yes

- name: Start Mongod
  service:
    name: mongod
    state: started

- name: Restart Mongod
  service:
    name: mongod
    state: restarted
